<a href="https://colab.research.google.com/github/Safaljoc/Concepts-and-Technologies-of-AI./blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Problem 1

# 1
arr = np.empty((2, 2))
print(arr)

# 2
print("-" * 50)
arr = np.ones((4, 2))
print(arr)

# 3
print("-" * 50)
arr = np.full((3, 3), dtype=int ,fill_value=99)
print(arr)

# 4
print("-" * 50)
arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_arr = np.zeros_like(arr)
print(zeros_arr)

# 5
print("-" * 50)
arr = np.array([[1, 2, 3], [4, 5, 6]])
ones_arr = np.ones_like(arr)
print(ones_arr)

# 6
print("-" * 50)
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

In [ ]:
import numpy as np

# Problem 2

# 1
arr = np.arange(10,50)
print(arr)

# 2
print("-" * 50)
arr = np.arange(0, 9)
reshaped_arr = np.reshape(arr, (3,3))
print(reshaped_arr)

# 3
print("-" * 50)
identity_matrix = np.eye(3)
print(identity_matrix)

# 4
print("-" * 50)
random_number_arr = np.random.random(30)
mean = random_number_arr.mean()
print(mean)

# 5
print("-" * 50)
arr = np.random.random((10,10))
min_value = arr.min()
max_value = arr.max()
print(min_value, max_value)

# 6
print("-" * 50)
arr = np.zeros(10)
arr[4] = 1
print(arr)

# 7
print("-" * 50)
arr = [1,2,0,0,4,0]
reversed_arr = np.flip(arr)
print(reversed_arr)

# 8
print("-" * 50)
rows, cols = 5, 5
arr = np.zeros((rows, cols), dtype=int)
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

# 9
print("-" * 50)
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

In [5]:
import numpy as np

# Problem 3
print("-" * 50)
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

# 1
sum_xy = np.add(x,y)
sum_vw = np.add(v,w)
print(sum_xy, sum_vw)

# 2
print("-" * 50)
subtract_xy = np.subtract(x,y)
subtract_vw = np.subtract(v,w)
print(subtract_xy, subtract_vw)

# 3
print("-" * 50)
multiply_x = np.multiply(x, 2)
multiply_y = np.multiply(y, 3)
multiply_v = np.multiply(v, 4)
multiply_w = np.multiply(w, 5)
print(multiply_x, multiply_y, multiply_v, multiply_w)

# 4
print("-" * 50)
x_squared = np.square(x)
y_squared = np.square(y)
v_squared = np.square(v)
w_squared = np.square(w)
print(x_squared, y_squared, v_squared, w_squared)

# 5
print("-" * 50)
dot_product_xy = np.dot(x,y)
dot_product_vw = np.dot(v,w)
print(dot_product_xy, dot_product_vw)

# 6
print("-" * 50)
concat_xy_row = np.concatenate((x,y), axis=0)
concat_vw_col = np.vstack((v, w))
print(concat_xy_row)
print(concat_vw_col)

# 7
# concat_xv = np.concatenate((x,v))
# print(concat_xv)
#The error happens because x is a 2D array while v is a 1D array, and NumPy cannot combine arrays that have different numbers of dimensions.

[[ 6  8]
 [10 13]] [20 22]
[[-4 -4]
 [-4 -3]] [-2 -2]
[[ 2  4]
 [ 6 10]] [[15 18]
 [21 24]] [36 40] [55 60]
--------------------------------------------------
[[ 1  4]
 [ 9 25]] [[25 36]
 [49 64]] [ 81 100] [121 144]
[[19 22]
 [50 58]] 219
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [6]:
import numpy as np

# Problem4

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A inverse:\n", A_inv)
print("A · A_inv:\n", I)
print(np.allclose(I, np.identity(2)))

# 2
print("-" * 50)
AB = np.dot(A, B)
BA = np.dot(B, A)
print("A · B:\n", AB)
print("B · A:\n", BA)
print(np.allclose(AB, BA))

# 3
print("-" * 50)
AB = np.dot(A, B)
AB_transpose = AB.T
BT_AT = np.dot(B.T, B.T)
print("(AB)T:\n", AB_transpose)
print("BT · AT:\n", BT_AT)
print(np.array_equal(AB_transpose, BT_AT))

# 4 and 5
print("-" * 50)
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A · A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
True
--------------------------------------------------
A · B:
 [[23 13]
 [51 29]]
B · A:
 [[36 44]
 [13 16]]
False
--------------------------------------------------
(AB)T:
 [[23 51]
 [13 29]]
BT · AT:
 [[31 12]
 [18  7]]
False
--------------------------------------------------
[[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
import numpy as np
import time

# 4.2 Experiment: How Fast is Numpy?
#1. Element-wise Addition:
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("time taken by python list:", end_time - start_time, "seconds")

arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
result_array = arr1 + arr2
end_time = time.time()
print("time taken by numpy array:", end_time - start_time, "seconds")

#2. Element-wise Multiplication:
print("-" * 50)
list1 = list(range(1000000))
list2 = list(range(1000000))

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()
print("time taken by python list:", end_time - start_time, "seconds")

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start_time = time.time()
result_np = arr1 * arr2
end_time = time.time()
print("time taken by numpy array:", end_time - start_time, "seconds")

#3. Dot Product
print("-" * 50)

#using python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()
print("dot product by python lists:", dot_list)
print("time taken by python lists:", end_time - start_time, "seconds")

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

# using numpy
start_time = time.time()
dot_np = np.dot(arr1, arr2)
end_time = time.time()
print("dot product by numpy", dot_np)
print("time taken by numpy:", end_time - start_time, "seconds")

#4. Matrix Multiplication
print("-" * 50)
size = 1000

# using python lists
A = [[1 for _ in range(size)] for _ in range(size)]
B = [[1 for _ in range(size)] for _ in range(size)]
result = [[0 for _ in range(size)] for _ in range(size)]
start = time.time()
for i in range(size):
    for j in range(size):
        total = 0
        for k in range(size):
            total += A[i][k] * B[k][j]
        result[i][j] = total
end = time.time()
print("time taken by python lists:", end - start, "seconds")

# using numpy
A_np = np.ones((size, size))
B_np = np.ones((size, size))
start = time.time()
np.dot(A_np, B_np)
end = time.time()
print("time taken by numpy:", end - start, "seconds")




time taken by python list: 0.15675902366638184 seconds
time taken by numpy array: 0.007669210433959961 seconds
--------------------------------------------------
time taken by python list: 0.36664700508117676 seconds
time taken by numpy array: 0.015691757202148438 seconds
--------------------------------------------------
dot product by python lists: 333332833333500000
time taken by python lists: 0.3680300712585449 seconds
dot product by numpy 333332833333500000
time taken by numpy: 0.006250619888305664 seconds
--------------------------------------------------
